# -*- coding: utf-8 -*-
"""fourier.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xB0bvuHDlOnqEaJzRhmhH8dvMoYPGgxB
"""

# Imports:

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import signal # Criação da Onda Quadrada base

plt.style.use('seaborn-v0_8') # Configuração de visualização

# Definindo a função que será a Série de Fourier:

"""
A função da Série de Fourier que será utilizada é dada por:
-> f(x) = 4/pi + \\sum_{n=1,3,5...}^{\\infty} (1/n)sin(n.pi.x/L)

Parâmetros:

x = Variável espacial.
n_term = Número do termo na série
L = Comprimento do período.
odd_n = Delimitação para o uso de números ímpares.
func_fourier = Série de Fourier.

Estamos tratando uma série que possui um somatório permitindo apenas
números ímpares.
"""

# Definindo a função da série de Fourier:

num_ciclos = 1 # Número de ciclos (não usado diretamente na soma, mas para o range de x)
L = np.pi # Comprimento do período
x = np.linspace(0, 2*num_ciclos*L, 1000) # Variável espacial

# prim_valor_serie = 0 # Não é mais necessário inicializar aqui
# prim_valor_iteracao = 1 # Não é mais necessário inicializar aqui
num_iteracoes = 5 # Número de iterações para o somatório

def fourier_onda_quadrada(x, n_term):

  odd_n = 2*n_term - 1 # Apenas números ímpares
  func_fourier = (4/np.pi) * (1/odd_n) * np.sin(odd_n*np.pi*x/L) # Série de Fourier
  return func_fourier

# Exibição de uma onda quadrada padrão para comparação:

fourier_sum = np.zeros_like(x) # Inicializa o somatório com zeros, do mesmo tamanho de x
original_square_wave = signal.square(np.pi * x / L) # Onda quadrada com período 2L
plt.figure(figsize=(12, 7))
plt.plot(x, original_square_wave, '--', label='Onda Quadrada Original', alpha=0.7)

"""
Definição do Somatório da Série de Fourier:

O somatório da série é feito como uma iteração, ou seja, a partir da
definição de uma condição de parada, a operação é feita até que a
condição seja satisfeita.
"""

for i in range(1, num_iteracoes + 1):
  fourier_sum += fourier_onda_quadrada(x, i)
  if i == 1 or i == 3 or i == num_iteracoes: # Plot de termos intermediários e o final
    plt.plot(x, fourier_sum, label= f"Soma com {i} termos")

plt.title("Aproximação da Onda Quadrada por Série de Fourier")
plt.xlabel('x')
plt.ylabel('f(x)')
plt.legend()
plt.grid(True)
plt.show()